-- Skema Supabase untuk portofolio dinamis.
-- Jalankan di Supabase Dashboard > SQL Editor.
-- Aplikasi tetap berjalan dengan data contoh bila env belum diisi.

create table if not exists profile (
  id integer primary key default 1,
  name text not null,
  role text not null,
  tagline text not null,
  bio text not null,
  location text not null,
  email text not null,
  avatar_url text not null,
  resume_url text not null default '',
  socials jsonb not null default '[]'::jsonb,
  constraint profile_singleton check (id = 1)
);

create table if not exists skills (
  id text primary key,
  name text not null,
  category text not null,
  level integer not null default 3 check (level between 1 and 5)
);

create table if not exists projects (
  id text primary key,
  slug text not null unique,
  title text not null,
  summary text not null,
  description text not null default '',
  tags text[] not null default '{}',
  image_url text not null default '',
  demo_url text,
  repo_url text,
  year integer not null default extract(year from now()),
  featured boolean not null default false
);

create table if not exists posts (
  id text primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null default '',
  tags text[] not null default '{}',
  cover_image text not null default '',
  published_at date not null default now(),
  reading_minutes integer not null default 5
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- Row Level Security.
-- Situs hanya membaca konten publik; penulisan dilakukan dari server
-- memakai service role key. Pesan kontak boleh ditulis siapa saja.
alter table profile enable row level security;
alter table skills enable row level security;
alter table projects enable row level security;
alter table posts enable row level security;
alter table messages enable row level security;

create policy "public read profile" on profile for select using (true);
create policy "public read skills" on skills for select using (true);
create policy "public read projects" on projects for select using (true);
create policy "public read posts" on posts for select using (true);
create policy "public insert messages" on messages for insert with check (true);
